name: Deploy Ma-Creatives-mainto Github Pages

on:
 push:
  branches: [main]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   -uses: withastro/action@v0
    with:
     path:
     node-version: 18
